version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/testrail.conf:/etc/nginx/conf.d/default.conf
      - testrail:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: shkrid/docker-testrail
    volumes:
      - testrail:/var/www/html
      - testrail-data:/opt/testrail/

  cron:
    image: shkrid/docker-testrail
    command: cron -f
    volumes:
      - testrail:/var/www/html
      - testrail-data:/opt/testrail/

  db:
    image: mysql:5.6
    env_file:
      - .env
    volumes:
      - testrail-mysql:/var/lib/mysql

volumes:
  testrail:
  testrail-data:
  testrail-mysql:
